platform :ios, '9.0'

inhibit_all_warnings!

pod 'AFNetworking', '2.6.0'
pod 'AFNetworkActivityLogger', '2.0.4'
pod 'MBProgressHUD', '0.9.1'
pod 'FastEasyMapping', '0.5.1'
pod 'UIViewController-KeyboardAdditions', '1.1'
